[package]
name = "clunky"
authors = ["Tin Švagelj <tin.svagelj@live.com>"]
version = "0.1.0"
edition = "2021"

[features]
default = ["wlr"]
x11 = []
wayland = ["dep:wayland-client", "dep:wayland-protocols"]
wlr = ["wayland", "dep:wayland-protocols-wlr"]

[dependencies]
# Data & scripting
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
rlua = "0.19"

fork = "0.1.20"
clap = { version = "4.0", features = ["derive"] }

# Rendering
image = "0.24"
glam = "0.24"

# Logging & errors
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"

# Util & macros
bitflags = "2.4"

# OS
tempfile = "3.3"
systemstat = "0.2"

# Wayland
wayland-client = { version = "0.31", optional = true }
wayland-protocols = { version = "0.31", optional = true, features = ["client"] }
wayland-protocols-wlr = { version = "0.2", optional = true, features = [
    "client",
] }
